project:
  type: website
  
website:
  title: "myTurbulenceModels"
  sidebar:
    style: "docked"
    contents:
      - text: Introduction
        href: index.qmd
      - section: "RANS models"
        contents:
          - text: "kOmegaTNT"
            href: RANS/kOmegaTNT.qmd
          - text: "kOmegaWilcox06"
            href: RANS/kOmegaWilcox06.qmd
          - text: "kOmegaSSTCC"
            href: RANS/kOmegaSSTCC.qmd
          - text: "kOmegaSSTCCM"
            href: RANS/kOmegaSSTCCM.qmd
          - text: "EARSM"
            href: RANS/EARSM.qmd
          - text: "EARSMWallin"
            href: RANS/EARSMWallin.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    bibliography: references.bib



